package exception

import "errors"

var EXTERNAL_UNKNOWN_ERROR = errors.New("EXTERNAL_UNKNOWN_ERROR")
